import { State } from "../state/appState.js";
import { TOP_GOAL_ROWS, createTopGoalRows } from "../data/topGoalTemplate.js";
import { findTeam, searchTeams } from "../services/teamSearch.js";
import { SimulationEngine } from "../services/simulation.js";

const $ = (id) => document.getElementById(id);
const emptyMatch = () => ({ home: "", away: "", score: "", played: false });
const esc = (value = "") => String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);

export const UIEngine = {
  normalizeTextInput(value, shouldTrim = true) { const cleaned = value.replace(/[^a-zA-Z,\s]/g, "").replace(/\s+/g, " ").slice(0, 240); return shouldTrim ? cleaned.trim() : cleaned; },
  clampRows() { let n = parseInt($("rowCount").value, 10); if (isNaN(n)) n = 7; n = Math.min(100, Math.max(1, n)); $("rowCount").value = n; return n; },
  hydrateFromGame() { const game = State.getActiveGame(); const rows = Math.max(7, game.matches?.length || 7); $("rowCount").value = rows; State.currentMatches = Array.from({ length: rows }, (_, i) => ({ ...emptyMatch(), ...(game.matches?.[i] || {}) })); this.renderAll(); },
  collectTopGoals() { return Array.from({ length: TOP_GOAL_ROWS }, (_, i) => ({ code: $(`topGoalCountry-${i}`)?.dataset.code || "", player: $(`topGoalPlayer-${i}`)?.value || "", goals: $(`topGoalGoals-${i}`)?.value || "" })); },
  saveActiveGame() { State.persistActiveGame(State.currentMatches, this.collectTopGoals()); this.renderMemoryControls(); },
  renderAll() { this.renderMemoryControls(); this.renderMatchEditor(); this.renderSchedule(); this.renderTopGoals(); },
  renderMemoryControls() { const select = $("memorySelect"); select.innerHTML = ""; Object.entries(State.store.memories).forEach(([slot, memory]) => select.add(new Option(memory.name, slot, Number(slot) === State.store.activeSlot))); const memory = State.getActiveMemory(); $("gameCounter").textContent = `${memory.games[memory.activeGameIndex].label} / ${memory.name}`; },
  renderMatchEditor() { const editor = $("matchEditor"); editor.innerHTML = ""; State.currentMatches.forEach((m, i) => { const row = document.createElement("div"); row.className = "match-edit-row"; row.innerHTML = `<span class="row-badge">${i === 0 ? "P1" : i + 1}</span><div class="smart-input-wrap"><input id="home-${i}" value="${esc(m.home || "")}" placeholder="Negara kiri" autocomplete="off"></div><input class="score-input" id="score-${i}" value="${esc(m.score || "")}" placeholder="0-0"><div class="smart-input-wrap"><input id="away-${i}" value="${esc(m.away || "")}" placeholder="Negara kanan" autocomplete="off"></div>`; editor.appendChild(row); this.bindTeamInput($(`home-${i}`), i, "home"); this.bindTeamInput($(`away-${i}`), i, "away"); $(`score-${i}`).addEventListener("input", (e) => { e.target.value = e.target.value.replace(/[^0-9\-]/g, "").slice(0, 7); State.currentMatches[i].score = e.target.value; State.currentMatches[i].played = Boolean(e.target.value); }); }); },
  bindTeamInput(input, index, side) { const wrap = input.parentElement; const apply = (code) => { input.value = code; State.currentMatches[index][side] = code; this.renderSchedule(); }; input.addEventListener("input", () => { const hit = findTeam(input.value); if (hit) State.currentMatches[index][side] = hit; this.showSuggestions(wrap, input.value, apply); }); input.addEventListener("blur", () => setTimeout(() => wrap.querySelector(".suggestions")?.remove(), 150)); },
  showSuggestions(wrap, query, onPick) { wrap.querySelector(".suggestions")?.remove(); const results = searchTeams(query); if (!results.length) return; const box = document.createElement("div"); box.className = "suggestions"; results.forEach(({ code, team }) => { const item = document.createElement("div"); item.className = "suggestion-item"; item.textContent = `${team.flag} ${team.name} (${code})`; item.addEventListener("mousedown", () => onPick(code)); box.appendChild(item); }); wrap.appendChild(box); },
  importTeams() { const raw = $("importInput"); raw.value = this.normalizeTextInput(raw.value); const parts = raw.value.toLowerCase().split(",").map(x => x.trim()).filter(Boolean); const parsed = parts.map(p => p.split(/\s*vs\s*/).map(findTeam)).filter(([h,a]) => h && a).map(([home, away]) => ({ home, away, score: "", played: false })); const rows = this.clampRows(); State.currentMatches = Array.from({ length: rows }, (_, i) => parsed[i] || emptyMatch()); this.renderMatchEditor(); this.renderSchedule(); },
  clearAll() { State.clearTimeouts(); $("predictBtn").disabled = false; $("importInput").value = ""; State.currentMatches = Array.from({ length: this.clampRows() }, emptyMatch); this.renderMatchEditor(); this.renderSchedule(); },
  renderSchedule() { const list = $("scheduleList"); list.innerHTML = ""; State.currentMatches.forEach((m, i) => { const h = State.teamsDB[m.home], a = State.teamsDB[m.away]; const row = document.createElement("div"); row.className = "match-row"; row.id = `row-${i}`; row.innerHTML = `<div class="team-container left-team"><div class="team-info"><span class="team-name ${h ? "" : "empty-name"}">${esc(h?.name || "---")}</span><div class="flag-box ${h ? "" : "empty-flag"}">${esc(h?.flag || "")}</div></div></div><div class="center-display" id="score-center-${i}"><div class="score-box"><span class="score-text">${esc(m.score || "-")}</span></div></div><div class="team-container right-team"><div class="team-info"><span class="team-name ${a ? "" : "empty-name"}">${esc(a?.name || "---")}</span><div class="flag-box ${a ? "" : "empty-flag"}">${esc(a?.flag || "")}</div></div></div>`; list.appendChild(row); }); },
  renderTopGoals() { const list = $("topGoalsList"); const saved = State.getActiveGame().topGoals?.length ? State.getActiveGame().topGoals : createTopGoalRows(); list.innerHTML = ""; saved.slice(0, TOP_GOAL_ROWS).forEach((g, i) => { const item = document.createElement("div"); item.className = "top-goal-item"; item.innerHTML = `<span class="goal-rank">${i + 1}</span><div class="top-goal-fields"><div class="smart-input-wrap"><input id="topGoalCountry-${i}" data-code="${esc(g.code || "")}" value="${esc(g.code || "")}" placeholder="JPN"></div><input id="topGoalPlayer-${i}" value="${esc(g.player || "")}" placeholder="Nama pemain"><input id="topGoalGoals-${i}" value="${esc(g.goals || "")}" placeholder="Goal" inputmode="numeric"></div>`; list.appendChild(item); this.bindTopGoalCountry($(`topGoalCountry-${i}`)); $(`topGoalGoals-${i}`).addEventListener("input", e => e.target.value = e.target.value.replace(/\D/g, "").slice(0, 3)); }); },
  bindTopGoalCountry(input) { const wrap = input.parentElement; input.addEventListener("input", () => { const code = findTeam(input.value); if (code) input.dataset.code = code; this.showSuggestions(wrap, input.value, c => { input.value = c; input.dataset.code = c; }); }); },
  predictAll() { const playable = State.currentMatches.filter(m => m.home && m.away && !m.played); if (!playable.length) return alert("Tidak ada pertandingan baru yang bisa diprediksi!"); $("predictBtn").disabled = true; State.currentMatches.forEach((m, i) => { if (!m.home || !m.away || m.played) return; const row = $(`row-${i}`); row.classList.add("loading"); const t = setTimeout(() => { const r = SimulationEngine.calculateScore(State.teamsDB[m.home], State.teamsDB[m.away]); m.score = `${r.h + r.exH}-${r.a + r.exA}`; m.played = true; $(`score-${i}`).value = m.score; row.classList.remove("loading"); this.renderSchedule(); $("predictBtn").disabled = false; }, 500 + i * 120); State.addTimeout(t); }); },
};
